### ISSUE TITLE
Some scripts enhancement suggestions 

### ISSUE THREAD

**Issue by jiere** [intel/cloud-native-ai-pipeline#165]
For [k8s_setup.sh](https://github.com/intel/cloud-native-ai-pipeline/blob/main/tools/prerequisites/k8s-setup.sh), 
1. When we only setup single node cluster, it is a MUST to run `kubectl taint nodes --all node-role.kubernetes.io/control-plane-`; when we setup multi-nodes cluster, it is best practice to prevent schedule pods on control-plane node, we'd better support both such scenarios.
2. Before setup the cluster, we'd better check if the node has joined other clusters before, or just simply run `rm -rf $HOME/.kube`

For [helm_manager.sh](https://github.com/intel/cloud-native-ai-pipeline/blob/main/tools/helm_manager.sh),
1. It is not user-friendly that we only mention the `image.registry` and `image.tag` settings as deploy prerequisites in [README.md](https://github.com/intel/cloud-native-ai-pipeline/blob/main/README.md#4-deployment), can we add check in scripts that if the two values above are still the default ones, throw out warning and exit the script?

What's more, I saw many blank contents in each chart's `values.yaml`, i.e. can we just remove words similar as [here](https://github.com/intel/cloud-native-ai-pipeline/blob/main/helm/inference/values.yaml#L14-L17)? I mean if the parameter in the yaml is not mandatory and never configured, can we just ignore it to make the config as simple as possible?

**Comment by leyao-daily** [comment]
For the helm manager script, we have configured here, user can easily set the two values.
```
-i          Install specified chart(s), or all charts if no chart is specified.
            When using -i, you can optionally set the image repository and tag:
            -r <repository_url>   Set the image repository (only valid with -i).
            -g <image_tag>       Set the image tag (only valid with -i).
```
And for the mentioned fields in `values.yaml`, we leave these fields to make it can be configured by the developers. It won't influence the setup, and it will keep consistency with the deployment files.

**Comment by jiere** [comment]
Yes, I did see the "-r" and "-g" options, they're clear for users, what I mean is the error handling or something like robust design.
since they are optional, so when they are not configured, we at least throw out error and let user to configure again, otherwise the helm deployment continues and fails finally. 
From another perspective, since the current default values of  `image.registry` and `image.tag` are totally meaningless, why not we change the "-r" and "-g" options to be mandatory? (maybe not applicable to redis-exporter?)
